In [34]:
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
import random
from sklearn.metrics import confusion_matrix

In [57]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [58]:
#ENG21AM3031 and ENG21AM3028
k = 31 #ENG21AM3031
data_points = 6900 #(31+28)*100 + 1000
training = int(data_points*0.8) # 80% of total dataset

In [59]:
X_train_ = X_train[:data_points]
y_train_ = y_train[:data_points]

In [60]:
X_train = X_train_[:training] # 80% of the dataset
y_train = y_train_[:training]

X_test = X_train_[training:data_points] #Last 20% of the dataset
y_test = y_train_[training:data_points]

In [61]:
X_test.shape

(1380, 28, 28)

In [62]:
knn = KNeighborsClassifier(n_neighbors=k)

In [63]:
#Function shuffles X_train, y_train and X_test, y_test and, changes the dimensions of X_train,X_test to 2D and returns two tuples.
def random_test():
    a = random.randint(0,100)
    X_shuf_train, y_shuf_train = shuffle(X_train, y_train, random_state=a)
    X_shuf_train = np.reshape(X_shuf_train, (training,28*28))
    X_shuf_test, y_shuf_test = shuffle(X_test, y_test, random_state=a)
    X_shuf_test = np.reshape(X_shuf_test, (data_points-training, 28*28))
    return (X_shuf_train, X_shuf_test, y_shuf_train, y_shuf_test)

In [64]:
conf_sum = np.zeros((10,10)) # Creating a new matrix of dimensions 10 x 10
sum = 0
for i in range(k): # Testing k (31) times 
    X_train,X_testing, y_train, y_testing = random_test()
    knn.fit(X_train, y_train)
    predict = knn.predict(X_testing)
    #print(f'{predict_} - {y_testing}')
    conf = confusion_matrix(y_testing, predict)
    conf_sum = conf + conf_sum # Summation of all confusion matrices 
    #https://stackoverflow.com/questions/39770376/scikit-learn-get-accuracy-scores-for-each-class
    sum += conf.diagonal()/conf.sum(axis=0)
for i in range(10):
    print(f'Precision of number {i} - {sum[i]/k}')
conf_avg = conf_sum/k
print(conf_avg)

Precision of number 0 - 0.9420289855072462
Precision of number 1 - 0.7938144329896911
Precision of number 2 - 0.9809523809523809
Precision of number 3 - 0.9403973509933783
Precision of number 4 - 0.957983193277311
Precision of number 5 - 0.9499999999999995
Precision of number 6 - 0.9225806451612899
Precision of number 7 - 0.9166666666666671
Precision of number 8 - 0.9724770642201832
Precision of number 9 - 0.7869822485207105
[[130.   0.   0.   0.   0.   1.   1.   0.   0.   0.]
 [  0. 154.   0.   0.   0.   0.   0.   1.   1.   0.]
 [  1.  17. 103.   1.   0.   0.   2.   3.   1.   1.]
 [  2.   4.   0. 142.   0.   1.   1.   3.   0.   3.]
 [  0.   2.   0.   0. 114.   0.   1.   0.   0.   8.]
 [  1.   4.   0.   4.   0. 114.   4.   0.   0.   1.]
 [  2.   2.   0.   0.   0.   1. 143.   0.   1.   0.]
 [  0.   7.   0.   0.   2.   0.   0. 110.   0.  20.]
 [  1.   4.   1.   3.   0.   3.   3.   1. 106.   3.]
 [  1.   0.   1.   1.   3.   0.   0.   2.   0. 133.]]


In [66]:
# Confirming the accuracy of the confusion matrix 
sum = 0
for i in range(10):
    for j in range(10):
        sum += conf_avg[i][j]
sum

1380.0